# Generated by Django 5.1.3 on 2025-05-18 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity_available', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Processing', max_length=50),
        ),
        migrations.CreateModel(
            name='PackageEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.IntegerField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.equipment')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.servicepackage')),
            ],
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='equipment',
            field=models.ManyToManyField(through='accounts.PackageEquipment', to='accounts.equipment'),
        ),
        migrations.DeleteModel(
            name='BookingStatus',
        ),
    ]
