# Generated by Django 5.1.3 on 2025-05-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_equipment_alter_booking_status_packageequipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='quantity_rented',
            field=models.IntegerField(default=0),
        ),
    ]
