# Generated by Django 5.1.3 on 2025-05-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_equipment_quantity_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Needs Repair', 'Needs Repair'), ('Excellent', 'Excellent')], default='Good', max_length=100),
        ),
    ]
