# Generated by Django 5.1.3 on 2025-05-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_equipment_current_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fulladdress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
