# Generated by Django 5.1.3 on 2025-05-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_booking_reviewed_remove_review_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='requested_admin',
            field=models.BooleanField(default=False),
        ),
    ]
