# Generated by Django 5.1.3 on 2025-05-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_review_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
