# Generated by Django 5.1.3 on 2025-08-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_booking_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
