# Generated by Django 5.1.3 on 2025-08-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_booking_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='professionalism',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='quality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='timeliness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='value_for_money',
            field=models.IntegerField(default=0),
        ),
    ]
