# Generated by Django 5.2.5 on 2025-08-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_review_professionalism_review_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='qty_maintenance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipment',
            name='qty_repair',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented'), ('Under Maintenance', 'Under Maintenance'), ('Under Repair', 'Under Repair'), ('Decommissioned', 'Decommissioned')], default='Available', max_length=50),
        ),
    ]
