# Generated by Django 5.2.5 on 2025-08-27 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_equipment_last_updated_equipment_qty_maintenance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='accounts.booking')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.IntegerField()),
                ('quantity_received', models.IntegerField(default=0)),
                ('confirmed', models.BooleanField(default=False)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.bookingchecklist')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.equipment')),
            ],
        ),
    ]
