# Generated by Django 5.2.5 on 2025-09-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/'),
        ),
    ]
