# Generated by Django 5.2.5 on 2025-09-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_servicepackage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='category',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Birthday', 'Birthday'), ('Corporate', 'Corporate'), ('Concert', 'Concert'), ('Seminar', 'Seminar'), ('Graduation', 'Graduation'), ('Awarding Ceremony', 'Awarding Ceremony'), ('Fundraising', 'Fundraising'), ('Fashion Show', 'Fashion Show'), ('Church', 'Church'), ('Conference', 'Conference'), ('School Event', 'School Event'), ('Charity Event', 'Charity Event')], default='Wedding', max_length=50),
        ),
        migrations.AlterField(
            model_name='packageequipment',
            name='quantity_required',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='equipment',
            field=models.ManyToManyField(related_name='service_packages', through='accounts.PackageEquipment', to='accounts.equipment'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
