# Generated by Django 5.2.5 on 2025-10-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_servicepackage_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='review_exists',
            field=models.BooleanField(default=False),
        ),
    ]
