# Generated by Django 5.2.5 on 2025-11-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_booking_rating_booking_review_exists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='rating',
        ),
        migrations.AddField(
            model_name='profile',
            name='barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
