# Generated by Django 5.2.5 on 2025-11-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_booking_rating_profile_barangay'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
