# Generated by Django 5.2.5 on 2025-11-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_booking_barangay'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
