# Generated by Django 5.2.5 on 2025-11-15 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_booking_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageequipment',
            name='quantity_required',
        ),
        migrations.AddField(
            model_name='packageequipment',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='packageequipment',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_equipments', to='accounts.servicepackage'),
        ),
    ]
