# Generated by Django 5.2.5 on 2025-11-16 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_remove_packageequipment_quantity_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageequipment',
            name='quantity',
        ),
        migrations.AddField(
            model_name='packageequipment',
            name='quantity_required',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='packageequipment',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.servicepackage'),
        ),
    ]
