# Generated by Django 5.2.5 on 2025-11-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_remove_packageequipment_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageequipment',
            name='quantity_required',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
