# Generated by Django 5.2.5 on 2025-12-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_packageequipment_quantity_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='audience_size',
        ),
    ]
