# Generated by Django 5.2.5 on 2026-01-02 04:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_remove_booking_audience_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingchecklist',
            name='checked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingchecklist',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingchecklist',
            name='checklist_type',
            field=models.CharField(choices=[('before', 'Before Event'), ('after', 'After Event')], default='before', max_length=20),
        ),
    ]
