# Generated by Django 5.2.5 on 2026-01-02 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_bookingchecklist_checked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingchecklist',
            name='checked_at',
        ),
        migrations.AddField(
            model_name='bookingchecklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookingchecklist',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='accounts.booking'),
        ),
        migrations.AlterField(
            model_name='bookingchecklist',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingchecklist',
            name='checklist_type',
            field=models.CharField(choices=[('BEFORE', 'Before Event'), ('AFTER', 'After Event')], default='BEFORE', max_length=10),
        ),
    ]
