# Generated by Django 5.2.5 on 2026-01-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_remove_bookingchecklist_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
