# Generated by Django 5.2.5 on 2026-01-04 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_booking_is_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('Added Stock', 'Added Stock'), ('Subtracted Stock', 'Subtracted Stock'), ('To Maintenance', 'To Maintenance'), ('Back From Maintenance', 'Back From Maintenance'), ('To Repair', 'To Repair'), ('Back From Repair', 'Back From Repair')], max_length=50)),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='accounts.equipment')),
            ],
        ),
    ]
