# Generated by Django 5.2.5 on 2026-01-05 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_maintenancehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='action',
            field=models.CharField(choices=[('add_stock', 'Added Stock'), ('subtract_stock', 'Removed Stock'), ('rented', 'Rented'), ('returned', 'Returned'), ('to_maintenance', 'Sent to Maintenance'), ('back_from_maintenance', 'Back from Maintenance'), ('to_repair', 'Sent to Repair'), ('back_from_repair', 'Back from Repair')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.booking'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.equipment'),
        ),
        migrations.DeleteModel(
            name='MaintenanceHistory',
        ),
    ]
