# Generated by Django 5.2.5 on 2026-01-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_inventorylog_action_alter_inventorylog_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='action',
            field=models.CharField(choices=[('add_stock', 'Added Stock'), ('subtract_stock', 'Subtracted Stock'), ('rented', 'Rented (Booking)'), ('returned', 'Returned (Booking)'), ('to_maintenance', 'Moved to Maintenance'), ('back_from_maintenance', 'Returned from Maintenance'), ('to_repair', 'Moved to Repair'), ('back_from_repair', 'Returned from Repair')], max_length=50),
        ),
    ]
