# Generated by Django 5.2.5 on 2026-01-05 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_inventorylog_notes_alter_inventorylog_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorylog',
            name='notes',
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='action',
            field=models.CharField(choices=[('add_stock', 'Stock Added'), ('subtract_stock', 'Stock Subtracted'), ('rented', 'Rented'), ('returned', 'Returned'), ('to_maintenance', 'Sent to Maintenance'), ('back_from_maintenance', 'Returned from Maintenance'), ('to_repair', 'Sent to Repair'), ('back_from_repair', 'Returned from Repair')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.equipment'),
        ),
    ]
