# Generated by Django 5.2.5 on 2026-01-05 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_remove_inventorylog_notes_alter_inventorylog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='action',
            field=models.CharField(choices=[('add_stock', 'Added Stock'), ('subtract_stock', 'Subtracted Stock'), ('to_maintenance', 'Moved to Maintenance'), ('back_from_maintenance', 'Returned from Maintenance'), ('to_repair', 'Moved to Repair'), ('back_from_repair', 'Returned from Repair'), ('rented', 'Rented'), ('returned', 'Returned')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.booking'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.equipment'),
        ),
    ]
